name: MarriagePaper
version: ${version}
main: com.beauver.minecraft.plugins.marriagePaper.MarriagePaper
api-version: '26.1.2'
authors: [ Beauver, Sebiann ]
description: Marriage mod

permissions:
  marriage.marry:
    description: Allows a player to marry, divorce and modify their relationship
    default: true
    children:
        marriage.marry.kiss: true
        marriage.marry.hug: true
        marriage.marry.tp: true
        marriage.marry.inventory: true
        marriage.marry.gift: true
        marriage.marry.fuck: false

  marriage.adopt:
    description: Allows a player to adopt other players as their children.
    default: true
    children:
        marriage.adopt.pat: true